apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: bgg-db-pvc
  namespace: workshop02
  annotations: 
    volume.beta.kubernetes.io/storage-provisioner: "dobs.csi.digitalocean.com"
    
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage