apiVersion: v1
kind: ServiceAccount

metadata:
  name: webui-user
  namespace: myns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: webui-user
  namespace: myns

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

subjects:
- kind: ServiceAccount
  name: webui-user
  namespace: myns
